import React from 'react';
import { BackButton } from '../components/PageChrome.jsx';
import { Flag,SurfaceBadge,EmptyState } from '../components/Common.jsx';
import { findDoublesTeam,findPlayer,findTournamentEdition } from '../sim/selectors.js';
import { fullName } from '../sim/generation.js';
import { universeYearLabel } from '../utils/year.js';

export default function MatchPage({universe,editionId,matchId,onBack,onPlayer}){
  const edition=findTournamentEdition(universe,editionId);
  const match=[...(edition?.matches||[]),...(edition?.qualifyingMatches||[])].find(m=>m.id===matchId);
  if(!edition||!match)return <div className="page"><BackButton onBack={onBack}/><EmptyState>Match not found.</EmptyState></div>;
  if(edition.championTeamId)return <DoublesMatch universe={universe} edition={edition} match={match} onBack={onBack} onPlayer={onPlayer}/>;
  const w=findPlayer(universe,match.winnerId),l=findPlayer(universe,match.loserId);
  return <div className="page detail-page"><BackButton onBack={onBack} label="Back to draw"/><header className="match-hero"><p>{edition.event.name} · {universeYearLabel(universe,edition.event.year)} · {match.round}</p><h1>{match.score}</h1><SurfaceBadge surface={edition.event.surface}/></header><section className="match-score-card"><button onClick={()=>w&&onPlayer(w.id)}><Flag code={w?.country}/><span>Winner</span><strong>{w?fullName(w):'Winner'}</strong><small>{w?.ranking?`World No. ${w.ranking}`:w?.juniorRanking?`Junior No. ${w.juniorRanking}`:''}</small></button><div><b>{match.score}</b><span>{formatDuration(match.durationMinutes)}</span></div><button onClick={()=>l&&onPlayer(l.id)}><Flag code={l?.country}/><span>Runner-up</span><strong>{l?fullName(l):'Opponent'}</strong><small>{l?.ranking?`World No. ${l.ranking}`:l?.juniorRanking?`Junior No. ${l.juniorRanking}`:''}</small></button></section><div className="two-column"><section className="panel"><h3>Why the match turned</h3><p>{match.explanation||'The winner combined the stronger performance in the decisive phases.'}</p><div className="tag-cloud">{(match.tags||[]).map(t=><span key={t}>{t}</span>)}</div></section><section className="panel"><h3>Match statistics</h3><div className="split-row"><span>Total games</span><strong>{match.totalGames||'—'}</strong></div><div className="split-row"><span>Duration</span><strong>{formatDuration(match.durationMinutes)||'—'}</strong></div><div className="split-row"><span>Winner aces</span><strong>{match.stats?.winnerAces||0}</strong></div><div className="split-row"><span>Loser aces</span><strong>{match.stats?.loserAces||0}</strong></div><div className="split-row"><span>Upset</span><strong>{match.upset?'Yes':'No'}</strong></div><div className="split-row"><span>Stage</span><strong>{match.qualifying?'Qualifying':'Main draw'}</strong></div></section></div></div>;
}

function DoublesMatch({universe,edition,match,onBack,onPlayer}){
  const winner=findDoublesTeam(universe,match.winnerId),loser=findDoublesTeam(universe,match.loserId);
  const winnerNames=match.winnerNames||winner?.playerNames||['Winning team'];
  const loserNames=match.loserNames||loser?.playerNames||['Opponents'];
  const winnerIds=winner?.playerIds||[];const loserIds=loser?.playerIds||[];
  return <div className="page detail-page"><BackButton onBack={onBack} label="Back to doubles draw"/><header className="match-hero"><p>{edition.event.name} · {universeYearLabel(universe,edition.event.year)} · {match.round}</p><h1>{match.score}</h1><SurfaceBadge surface={edition.event.surface}/></header><section className="match-score-card doubles-score"><div className="team-side"><span>Winners</span>{winnerNames.map((name,i)=><button className="player-link" key={`${name}-${i}`} onClick={()=>winnerIds[i]&&onPlayer(winnerIds[i])}><Flag code={match.winnerCountries?.[i]||winner?.countries?.[i]}/>{name}</button>)}</div><div><b>{match.score}</b><span>{formatDuration(match.durationMinutes)}</span></div><div className="team-side"><span>Opponents</span>{loserNames.map((name,i)=><button className="player-link" key={`${name}-${i}`} onClick={()=>loserIds[i]&&onPlayer(loserIds[i])}><Flag code={match.loserCountries?.[i]||loser?.countries?.[i]}/>{name}</button>)}</div></section><div className="two-column"><section className="panel"><h3>Partnership context</h3><p>{winner?`${winner.type} partnership with ${Math.round(winner.chemistry)} chemistry and a ${winner.rating} tactical rating.`:'The winning pair combined serve, return, volley and chemistry more effectively.'}</p><div className="tag-cloud">{(match.tags||[]).map(t=><span key={t}>{t}</span>)}</div></section><section className="panel"><h3>Match statistics</h3><div className="split-row"><span>Total games</span><strong>{match.totalGames||'—'}</strong></div><div className="split-row"><span>Duration</span><strong>{formatDuration(match.durationMinutes)||'—'}</strong></div><div className="split-row"><span>Round</span><strong>{match.round}</strong></div></section></div></div>;
}
function formatDuration(value){return value?`${Math.floor(value/60)}h ${value%60}m`:'';}
