import React,{useMemo,useState} from 'react';
import { Flag,Meter,RarityBadge,SurfaceBadge,EmptyState } from '../components/Common.jsx';
import { BackButton,Tabs,Stat } from '../components/PageChrome.jsx';
import { careerMultiplier,fullName } from '../sim/generation.js';
import { conditionLabel,ensurePlayerData } from '../sim/migrations.js';
import { findPlayer,playerMatches,signatureTournament,surfaceCareer,tournamentKey } from '../sim/selectors.js';
import { rivalryExtremes } from '../sim/rivalries.js';
import { universeYearLabel } from '../utils/year.js';

const SKILLS=[['serve','Serve'],['forehand','Forehand'],['backhand','Backhand'],['volley','Volley'],['return','Return'],['footwork','Footwork'],['endurance','Endurance'],['mentality','Mentality'],['tactics','Tactics']];
const SURFACES=['Hard','Clay','Grass','Indoor'];
function fmtMinutes(value){if(!value)return '—';return `${Math.floor(value/60)}h ${value%60}m`;}
function percent(w,l){return w+l?Math.round(w/(w+l)*100):0;}

function RivalryColumn({title,subtitle,rows,player,universe,onPlayer,onRivalry,tone}){
  return <section className="panel rivalry-column"><h3>{title}<span>{subtitle}</span></h3>{rows.length?<div className="rivalry-list">{rows.map(row=>{const opp=findPlayer(universe,row.opponentId);return <div className="rivalry-list-row" key={row.opponentId}><button onClick={()=>onPlayer(row.opponentId)}><div><Flag code={opp?.country}/><strong>{opp?fullName(opp):'Unknown'}</strong><small>{row.meetings} meetings · {row.majors} at majors · {row.finals} finals</small></div><div><b>{row.wins}-{row.losses}</b><span className={`rivalry-balance ${tone}`}>{row.balance>0?'+':''}{row.balance}</span></div></button>{opp&&<button className="secondary mini" onClick={()=>onRivalry?.(player.id,opp.id)}>Rivalry page</button>}</div>})}</div>:<div className="rivalry-empty">No meaningful {tone==='positive'?'favorable':'unfavorable'} rivalry yet.</div>}</section>;
}

function CareerLine({points,currentIndex,label,valueLabel}){
  const width=920,height=270,pad=42,values=points.map(point=>point.value),min=Math.min(...values,0.62),max=Math.max(...values,1.04),range=Math.max(.01,max-min);
  const coords=points.map((point,index)=>({x:pad+(index/Math.max(1,points.length-1))*(width-pad*2),y:height-pad-((point.value-min)/range)*(height-pad*2),...point}));
  const current=coords[Math.max(0,Math.min(currentIndex,coords.length-1))];
  return <div className="career-line-wrap"><svg className="career-line" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} className="chart-axis"/><line x1={pad} y1={pad} x2={pad} y2={height-pad} className="chart-axis"/>{[0,.25,.5,.75,1].map(t=>{const y=pad+t*(height-pad*2);return <line key={t} x1={pad} y1={y} x2={width-pad} y2={y} className="chart-grid"/>})}<polyline points={coords.map(point=>`${point.x},${point.y}`).join(' ')} className="career-path" fill="none"/>{coords.map((point,index)=><g key={`${point.label}-${index}`}><circle cx={point.x} cy={point.y} r={index===currentIndex?7:3.5} className={index===currentIndex?'career-dot current':'career-dot'}/>{(index%Math.max(1,Math.ceil(points.length/12))===0||index===points.length-1)&&<text x={point.x} y={height-14} textAnchor="middle" className="chart-label">{point.label}</text>}</g>)}{current&&<><line x1={current.x} y1={pad-8} x2={current.x} y2={height-pad} className="current-marker"/><rect x={Math.min(width-145,Math.max(48,current.x-57))} y={Math.max(8,current.y-50)} width="114" height="28" rx="6" className="current-label-bg"/><text x={Math.min(width-88,Math.max(105,current.x))} y={Math.max(27,current.y-31)} textAnchor="middle" className="current-label">WE ARE HERE</text></>}</svg><div className="chart-caption"><span>{label}</span><strong>{valueLabel}</strong></div></div>;
}

export default function PlayerPage({universe,playerId,onBack,onPlayer,onTournament,onRivalry,isFollowed=false,onToggleFollow}){
  const [tab,setTab]=useState('Overview');
  const player=findPlayer(universe,playerId);
  if(!player)return <div className="page"><BackButton onBack={onBack}/><EmptyState>Player not found in this universe.</EmptyState></div>;
  ensurePlayerData(player,universe.year);
  const matches=useMemo(()=>playerMatches(universe,player.id),[universe,player.id]);
  const rivalryGroups=useMemo(()=>rivalryExtremes(universe,player.id,5),[universe,player.id]);
  const seasons=[...(player.career?.seasons||[]),...(player.season?[player.season]:[])].sort((a,b)=>b.year-a.year);
  const doublesSeason=player.doublesSeason||{year:universe.year,matches:0,wins:0,losses:0,titles:0,majors:0,points:0,tournaments:0,results:[]};
  const doublesCareer=player.doublesSpecialist?(player.doublesCareer||{}):{matches:player.career.doublesMatches||0,wins:player.career.doublesWins||0,losses:player.career.doublesLosses||0,titles:player.career.doublesTitles||0,majors:player.career.doublesMajors||0,weeksNo1:player.career.doublesWeeksNo1||0,peakRanking:player.career.doublesPeakRanking||999};
  const careerSeasons=player.doublesSpecialist?[...(player.career.doublesSeasons||[]),doublesSeason].sort((a,b)=>b.year-a.year):seasons;
  const currentSeason=player.doublesSpecialist?doublesSeason:player.season;
  const signature=signatureTournament(player);
  const majorResults=careerSeasons.flatMap(s=>(s.results||[]).filter(r=>r.level==='Grand Slam').map(r=>({...r,year:s.year}))).sort((a,b)=>b.year-a.year||a.week-b.week);
  const partnerships=[...(player.career.partnershipLog||[])];
  const styleRows=useMemo(()=>{
    const map=new Map();
    for(const match of matches){const opp=findPlayer(universe,match.winnerId===player.id?match.loserId:match.winnerId);if(!opp)continue;const row=map.get(opp.style)||{style:opp.style,wins:0,losses:0};if(match.winnerId===player.id)row.wins+=1;else row.losses+=1;map.set(opp.style,row);}
    return [...map.values()].sort((a,b)=>(b.wins+b.losses)-(a.wins+a.losses));
  },[matches,player.id,universe]);
  const ranking=player.status==='retired'?`Retired${player.retirementYear?` · ${universeYearLabel(universe,player.retirementYear)}`:''}`:player.junior?`Junior No. ${player.juniorRanking}`:player.doublesSpecialist?`Doubles No. ${player.doublesRanking}`:`World No. ${player.ranking}`;
  const hallEntry=(universe.hallOfFame||[]).find(row=>row.playerId===player.id);
  const congested=(player.weeksPlayedConsecutive||0)>=3||player.fatigue>=65;
  const enduranceWarning=player.skills.endurance<60;
  return <div className="page detail-page">
    <BackButton onBack={onBack} label="Back to previous page"/>
    <header className="player-hero">
      <div><p>{player.tour} · {ranking}</p><h1>{fullName(player)}</h1><div className="player-tags"><Flag code={player.country}/><RarityBadge rarity={player.rarity}/><SurfaceBadge surface={player.preferredSurface}/><span className="badge neutral">{player.style}</span><span className={`badge personality personality-${String(player.socialPersonality||'stoic').toLowerCase()}`}>{player.socialPersonality||'Stoic'}</span>{hallEntry&&<span className="badge hall-badge">Hall of Fame</span>}{player.injury&&<span className="badge danger">Injured · {player.injury.weeksRemaining}w</span>}</div></div>
      <div className="player-hero-actions"><button className={`follow-button ${isFollowed?'active':''}`} onClick={onToggleFollow}>{isFollowed?'★ Followed':'☆ Follow player'}</button><div className="hero-rating"><span>Current</span><strong>{player.currentRating}</strong><small>Maximum {player.maxRating}</small></div></div>
    </header>
    {(congested||enduranceWarning||player.protectedRanking)&&<section className="alert-strip">{congested&&<span>Schedule congestion: recovery recommended</span>}{enduranceWarning&&<span>Best-of-five endurance warning</span>}{player.protectedRanking&&<span>Protected ranking: No. {player.protectedRanking}</span>}</section>}
    <Tabs items={['Overview','Current Season','Career','Matchups','Development','Records']} active={tab} onChange={setTab}/>

    {tab==='Overview'&&<>
      <section className="detail-stat-grid"><Stat label="Age" value={player.age}/><Stat label="Peak ranking" value={player.career.peakRanking<999?`No. ${player.career.peakRanking}`:'—'}/><Stat label="Social personality" value={player.socialPersonality||'Stoic'}/><Stat label="Fame" value={(player.fame||0).toLocaleString()}/><Stat label="Career phase" value={player.curveType}/><Stat label="Condition" value={conditionLabel(player)}/><Stat label="Hand" value={player.handedness}/><Stat label="Backhand" value={player.backhand}/><Stat label="Height" value={`${player.heightCm} cm`}/><Stat label="Academy" value={player.academy}/>{(player.doublesSpecialist||player.doublesRanking<999)&&<Stat label="Doubles rank" value={player.doublesRanking<999?`No. ${player.doublesRanking}`:'—'}/>}</section>
      <div className="two-column wide-left"><section className="panel"><h3>Condition</h3><div className="condition-grid"><Meter label="Match shape" value={player.shape}/><Meter label="Fatigue" value={player.fatigue}/><Meter label="Health" value={player.health}/>{(player.doublesSpecialist||doublesSeason.matches>0)&&<Meter label="Doubles shape" value={player.doublesShape}/>}</div><h3>Core skills</h3><div className="skills-grid">{SKILLS.map(([k,l])=><Meter key={k} label={l} value={player.skills[k]} compact/>)}</div></section><section className="panel"><h3>Surface profile</h3>{SURFACES.map(surface=><Meter key={surface} label={surface} value={player.surfaceAffinity[surface]} compact/>)}<h3>Identity markers</h3><div className="tag-cloud">{[...(player.personalityTags||[]),...(player.narrativeTags||[])].map(t=><span key={t}>{t}</span>)}</div><dl className="profile-list"><div><dt>Injury resilience</dt><dd>{player.injuryResilience}</dd></div><div><dt>Retirement inclination</dt><dd>{player.retirementInclination}</dd></div><div><dt>Doubles potential</dt><dd>{player.doublesPotential}</dd></div><div><dt>Birthday</dt><dd>{player.birthMonth}/{player.birthDay} · age {player.age}</dd></div></dl></section></div>
    </>}

    {tab==='Current Season'&&<>
      <section className="detail-stat-grid"><Stat label="Record" value={`${currentSeason.wins||0}-${currentSeason.losses||0}`}/><Stat label="Titles" value={currentSeason.titles||0}/><Stat label="Grand Slams" value={currentSeason.majors||0}/><Stat label={player.doublesSpecialist?'Doubles points':'Race points'} value={(player.doublesSpecialist?currentSeason.points:(currentSeason.racePoints||0)).toLocaleString()}/><Stat label="Tournaments" value={currentSeason.tournaments||0}/><Stat label={player.doublesSpecialist?'Doubles rank':'Withdrawals'} value={player.doublesSpecialist?(player.doublesRanking<999?`No. ${player.doublesRanking}`:'—'):(currentSeason.withdrawals?.length||0)}/></section>
      <div className="two-column wide-left"><section className="panel"><h3>Chronological schedule and results</h3>{currentSeason.results?.length?<div className="result-ledger">{[...currentSeason.results].sort((a,b)=>a.week-b.week).map((r,i)=><button key={`${r.eventId}-${i}`} onClick={()=>onTournament(tournamentKey(player.tour,r.event))}><span>W{r.week}</span><div><strong>{r.event}</strong><small>{r.level} · {r.surface} · {r.entryType||r.partnerNames?.join(' / ')||'Entry'}</small></div><b>{r.round}</b><em>{r.points} pts</em></button>)}</div>:<EmptyState>No results yet this season.</EmptyState>}</section><section className="panel">{player.doublesSpecialist?<><h3>Doubles profile</h3><div className="split-row"><span>Tactical rating</span><strong>{player.doublesRating||player.doublesTacticalRating}</strong></div><div className="split-row"><span>Match shape</span><strong>{Math.round(player.doublesShape||0)}</strong></div><div className="split-row"><span>Career record</span><strong>{doublesCareer.wins||0}-{doublesCareer.losses||0}</strong></div><div className="split-row"><span>Partnerships</span><strong>{partnerships.length}</strong></div></>:<><h3>Intended targets</h3><div className="target-list">{(player.season.intendedTargets||[]).map(name=><button key={name} onClick={()=>onTournament(tournamentKey(player.tour,name))}>{name}</button>)}</div><h3>Surface splits</h3>{SURFACES.map(surface=>{const w=player.season.surfaceWins?.[surface]||0,l=player.season.surfaceLosses?.[surface]||0;return <div className="split-row" key={surface}><SurfaceBadge surface={surface}/><strong>{w}-{l}</strong><span>{percent(w,l)}%</span></div>})}{player.season.withdrawals?.length>0&&<><h3>Withdrawals / injuries</h3>{player.season.withdrawals.map((w,i)=><p className="notice-row" key={i}>Week {w.week}: {w.reason} ({w.weeks} weeks)</p>)}</>}</>}</section></div>
      {!player.doublesSpecialist&&doublesSeason.matches>0&&<section className="panel"><h3>Doubles this season</h3><div className="detail-stat-grid compact"><Stat label="Record" value={`${doublesSeason.wins}-${doublesSeason.losses}`}/><Stat label="Titles" value={doublesSeason.titles}/><Stat label="Points" value={doublesSeason.points.toLocaleString()}/><Stat label="Rank" value={player.doublesRanking<999?`No. ${player.doublesRanking}`:'—'}/></div></section>}
    </>}

    {tab==='Career'&&<>
      <section className="detail-stat-grid">{player.doublesSpecialist?<><Stat label="Doubles record" value={`${doublesCareer.wins||0}-${doublesCareer.losses||0}`}/><Stat label="Doubles titles" value={doublesCareer.titles||0}/><Stat label="Doubles majors" value={doublesCareer.majors||0}/><Stat label="Weeks No. 1" value={doublesCareer.weeksNo1||0}/><Stat label="Peak ranking" value={(doublesCareer.peakRanking||999)<999?`No. ${doublesCareer.peakRanking}`:'—'}/><Stat label="Conversion year" value={player.career.doublesConversionYear?universeYearLabel(universe,player.career.doublesConversionYear):'Career specialist'}/></>:<><Stat label="Career record" value={`${player.career.wins}-${player.career.losses}`}/><Stat label="Singles titles" value={player.career.titles}/><Stat label="Grand Slams" value={player.career.majors}/><Stat label="Masters / 1000" value={player.career.masters||0}/><Stat label="Weeks No. 1" value={player.career.weeksNo1}/><Stat label="Year-end No. 1" value={player.career.yearEndNo1}/><Stat label="Doubles titles" value={doublesCareer.titles||0}/><Stat label="Doubles peak" value={(doublesCareer.peakRanking||player.doublesRanking||999)<999?`No. ${doublesCareer.peakRanking||player.doublesRanking}`:'—'}/><Stat label="National-team titles" value={player.career.nationalTeamTitles||0}/></>}</section>
      <section className="panel"><h3>Year-by-year record</h3><div className="table-wrap"><table className="data-table career-season-table"><thead><tr><th>Year</th><th>W-L</th><th>Rank best</th><th>Titles</th><th>Majors</th><th>Points</th><th>Tournaments</th></tr></thead><tbody>{careerSeasons.map(season=>{const titles=(season.titleList?.length?season.titleList:(player.career?.titleLog||[]).filter(row=>row.year===season.year));return <React.Fragment key={season.year}><tr><td><strong>{universeYearLabel(universe,season.year)}</strong></td><td>{season.wins||0}-{season.losses||0}</td><td>{season.bestRanking&&season.bestRanking<999?`No. ${season.bestRanking}`:'—'}</td><td>{season.titles||0}</td><td>{season.majors||0}</td><td>{(season.points||0).toLocaleString()}</td><td>{season.tournaments||0}</td></tr><tr className="season-title-row"><td colSpan="7">{titles.length?<div className="season-title-list">{titles.map((title,index)=><button key={`${title.event}-${index}`} onClick={()=>onTournament(tournamentKey(player.tour,title.event))}><strong>{title.event}</strong><span>{title.level||'Title'} · {title.surface||'—'}</span></button>)}</div>:<span className="muted">No titles this year.</span>}</td></tr></React.Fragment>})}</tbody></table></div></section>
      <div className="two-column"><section className="panel"><h3>{player.doublesSpecialist?'Doubles Grand Slam rounds':'Grand Slam rounds'}</h3>{majorResults.length?<div className="history-list">{majorResults.slice(0,32).map((r,i)=><button key={`${r.year}-${r.event}-${i}`} onClick={()=>onTournament(tournamentKey(player.tour,r.event))}><strong>{universeYearLabel(universe,r.year)} · {r.event}</strong><span>{r.round}</span><small>{r.surface} · {r.points} pts</small></button>)}</div>:<p className="muted">No Grand Slam appearances stored.</p>}</section><section className="panel"><h3>Titles by level</h3>{Object.entries(player.career.titlesByLevel||{}).sort((a,b)=>b[1]-a[1]).map(([level,n])=><div className="split-row" key={level}><span>{level}</span><strong>{n}</strong></div>)}<h3>National teams</h3><p>Appearances: <strong>{player.career.nationalTeamAppearances||0}</strong></p><p>Rubber record: <strong>{player.career.nationalTeamWins||0}-{player.career.nationalTeamLosses||0}</strong></p><p>Olympic medals: <strong>{player.career.olympicMedals||0}</strong></p></section></div>
      <section className="panel"><h3>Doubles and partnership history</h3>{partnerships.length?<div className="history-list">{partnerships.map((p,i)=><div key={`${p.teamId}-${i}`}><strong>{p.partnerNames?.join(' / ')||'Partner'}</strong><span>{p.type}</span><small>Started {universeYearLabel(universe,p.startYear)}</small></div>)}</div>:<p className="muted">No stored partnership history.</p>}</section>
      <section className="panel"><h3>Awards</h3>{player.career.awards?.length?player.career.awards.map((a,i)=><p key={i}>{universeYearLabel(universe,a.year)} · <strong>{a.name}</strong></p>):<p className="muted">No annual awards yet.</p>}</section>
    </>}

    {tab==='Matchups'&&<><div className="rivalry-columns"><RivalryColumn title="Best positive balances" subtitle="Top five" rows={rivalryGroups.positive} player={player} universe={universe} onPlayer={onPlayer} onRivalry={onRivalry} tone="positive"/><RivalryColumn title="Most difficult rivals" subtitle="Top five" rows={rivalryGroups.negative} player={player} universe={universe} onPlayer={onPlayer} onRivalry={onRivalry} tone="negative"/></div><div className="two-column"><section className="panel"><h3>Performance by opponent style</h3>{styleRows.map(row=><div className="split-row" key={row.style}><span>{row.style}</span><strong>{row.wins}-{row.losses}</strong><em>{percent(row.wins,row.losses)}%</em></div>)}<h3>Match-pattern record</h3><p>Five-set: <strong>{player.career.fiveSetWins}-{player.career.fiveSetLosses}</strong></p><p>Deciding sets: <strong>{player.career.decidingSetWins}-{player.career.decidingSetLosses}</strong></p></section><section className="panel"><h3>Recent matches</h3>{matches.slice(0,12).map(m=>{const opp=findPlayer(universe,m.winnerId===player.id?m.loserId:m.winnerId);return <div className="recent-match" key={m.id}><span className={m.winnerId===player.id?'win':'loss'}>{m.winnerId===player.id?'W':'L'}</span><div><strong>{opp?fullName(opp):'Opponent'}</strong><small>{m.event.name} · {m.round} · {m.surface}</small></div><b>{m.score}</b></div>})}</section></div><div className="rivalry-storage-note">Only meaningful rivalries are preserved permanently. Recent match history is capped, while career rivalry pages retain aggregate meetings, surface records, major/final counts and selected important chapters.</div></>}

    {tab==='Development'&&<><section className="panel"><h3>Career curve</h3><CareerLine points={Array.from({length:23},(_,index)=>{const age=15+index;return {label:age,value:careerMultiplier(player.curveType,age,player.peakAge)}})} currentIndex={Math.max(0,Math.min(22,player.age-15))} label="Annual ability multiplier by age" valueLabel={`Current ${player.currentMultiplier.toFixed(2)} · Next year ${careerMultiplier(player.curveType,player.age+1,player.peakAge).toFixed(2)}`}/><p className="muted">Maximum base rating {player.maxRating}. The marker shows whether the next season is expected to rise, hold or decline.</p></section>{(player.developmentHistory||[]).length>1&&<section className="panel"><h3>Observed rating history</h3><CareerLine points={(player.developmentHistory||[]).map(row=>({label:universeYearLabel(universe,row.year),value:row.rating}))} currentIndex={(player.developmentHistory||[]).length-1} label="Current rating by season" valueLabel={`Rating ${player.currentRating}`}/></section>}</>}

    {tab==='Records'&&<div className="two-column"><section className="panel"><h3>Personal records</h3><dl className="record-dl"><div><dt>Longest winning streak</dt><dd>{player.career.longestWinStreak||0}</dd></div><div><dt>Biggest upset</dt><dd>{player.career.biggestUpset?`No. ${player.career.biggestUpset.opponentRanking} ${player.career.biggestUpset.opponent}`:'—'}</dd></div><div><dt>Longest match</dt><dd>{player.career.longestMatch?`${fmtMinutes(player.career.longestMatch.durationMinutes)} vs ${player.career.longestMatch.opponent}`:'—'}</dd></div><div><dt>Best surface</dt><dd>{SURFACES.map(s=>[s,surfaceCareer(player,s)]).sort((a,b)=>b[1].pct-a[1].pct)[0][0]}</dd></div><div><dt>Signature tournament</dt><dd>{signature?`${signature[0]} (${signature[1]} titles)`:'—'}</dd></div><div><dt>Doubles record</dt><dd>{player.doublesSpecialist?`${player.doublesCareer?.wins||0}-${player.doublesCareer?.losses||0}`:`${player.career.doublesWins||0}-${player.career.doublesLosses||0}`}</dd></div></dl></section><section className="panel"><h3>Surface career ledger</h3>{SURFACES.map(surface=>{const r=surfaceCareer(player,surface);return <div className="surface-record" key={surface}><SurfaceBadge surface={surface}/><strong>{r.wins}-{r.losses}</strong><span>{r.pct}% wins</span><b>{r.titles} titles</b></div>})}</section></div>}
  </div>;
}
