import React,{useMemo,useState} from 'react';
import { EmptyState,Flag,SurfaceBadge } from '../components/Common.jsx';
import { BackButton,Tabs,Stat } from '../components/PageChrome.jsx';
import { countryByCode } from '../data/countries.js';
import { LEVEL_POINTS } from '../data/calendar.js';
import { findDoublesTeam,findPlayer,tournamentFamily,tournamentStats } from '../sim/selectors.js';
import { fullName } from '../sim/generation.js';

export default function TournamentDetailPage({universe,tour,name,onBack,onPlayer,onMatch,onSimulate}){
  const family=tournamentFamily(universe,tour,name);
  const availableYears=[...new Set([universe.year,...family.editions.map(e=>e.event.year)])].sort((a,b)=>b-a);
  const [year,setYear]=useState(universe.year);
  const [tab,setTab]=useState('Overview');
  const edition=family.editions.find(e=>e.event.year===year)||null;
  const event=edition?.event||family.calendar||family.editions[0]?.event;
  const stats=useMemo(()=>tournamentStats(universe,tour,name),[universe,tour,name]);
  if(!event)return <div className="page"><BackButton onBack={onBack}/><EmptyState>Tournament not found.</EmptyState></div>;
  if(family.kind==='team')return <TeamTournamentView universe={universe} tour={tour} name={name} family={family} event={event} edition={edition} year={year} setYear={setYear} availableYears={availableYears} tab={tab} setTab={setTab} onBack={onBack} onPlayer={onPlayer} onSimulate={onSimulate}/>;
  if(family.kind==='doubles')return <DoublesTournamentView universe={universe} tour={tour} name={name} family={family} event={event} edition={edition} year={year} setYear={setYear} availableYears={availableYears} tab={tab} setTab={setTab} onBack={onBack} onPlayer={onPlayer} onMatch={onMatch} onSimulate={onSimulate}/>;
  const previous=family.editions.find(e=>e.event.year===(universe.year-1))||family.editions.find(e=>e.event.year<universe.year);
  const champion=edition&&findPlayer(universe,edition.championId);
  const byRound=(edition?.matches||[]).reduce((g,m)=>{(g[m.round]??=[]).push(m);return g;},{});
  const repeatWinners=stats.titleLeaders.filter(r=>r.value>1);
  const notableFinals=family.editions.map(e=>({edition:e,match:e.matches?.find(m=>m.round==='F')})).filter(r=>r.match&&(r.match.upset||r.match.tags?.includes('marathon')||r.match.tags?.includes('comeback')));
  return <div className="page detail-page"><BackButton onBack={onBack} label="Back to previous page"/>
    <header className="tournament-hero"><div><p>{tour} · {event.level}</p><h1>{name}</h1><span>{event.location} · {event.dates||`Week ${event.week}`}</span></div><SurfaceBadge surface={event.surface}/></header>
    <Tabs items={['Overview','Current Year','History','Stats']} active={tab} onChange={setTab}/>

    {tab==='Overview'&&<><section className="detail-stat-grid"><Stat label="Location" value={event.location}/><Stat label="Surface" value={event.surface}/><Stat label="Level" value={event.level}/><Stat label="Champion points" value={championPoints(event.level).toLocaleString()}/><Stat label="Draw" value={event.drawSize}/><Stat label="Qualifying draw" value={event.qualifyingDrawSize||'—'}/><Stat label="Week" value={event.week}/><Stat label="Defending champion" value={previous?.championName||'First edition'}/></section>{edition?<section className="champion-banner"><span>{year} champion</span><button onClick={()=>onPlayer(edition.championId)}>{edition.championName}</button><p>defeated {edition.finalistName}</p></section>:<section className="panel upcoming-edition"><h3>Upcoming edition</h3><p>The draw will be generated when simulation reaches week {event.week}. Entry is determined by ranking, qualifying, wild cards, junior exemptions, protected ranking, surface fit, schedule and health.</p>{event.year===universe.year&&event.week>=universe.week&&!universe.seasonEnded&&<button className="primary-action" onClick={()=>onSimulate?.(event.week)}>Simulate to {name}</button>}</section>}</>}

    {tab==='Current Year'&&<><div className="edition-selector"><label>Edition <select value={year} onChange={e=>setYear(Number(e.target.value))}>{availableYears.map(y=><option key={y}>{y}</option>)}</select></label>{champion&&<span>Champion: <button className="player-link" onClick={()=>onPlayer(champion.id)}>{fullName(champion)}</button></span>}</div>{edition?<><section className="panel"><h3>Seeds and entry routes</h3><div className="entry-grid">{(edition.entryMeta||edition.entryIds?.map((id,index)=>({id,type:edition.seeds?.find(s=>s.id===id)?`Seed ${edition.seeds.find(s=>s.id===id).rank}`:'Junior entry',effectiveRank:findPlayer(universe,id)?.juniorRanking||999}))||[]).map(meta=>{const p=findPlayer(universe,meta.id);return <button key={meta.id} onClick={()=>onPlayer(meta.id)}><span>{meta.type}</span><strong>{p?fullName(p):meta.id}</strong><small>{meta.effectiveRank<999?`No. ${meta.effectiveRank}`:'Unranked'}</small></button>})}</div></section>{edition.qualifyingMatches?.length>0&&<section className="panel"><h3>Qualifying draw</h3><div className="match-list compact">{edition.qualifyingMatches.map(m=><button key={m.id} onClick={()=>onMatch(edition.id,m.id)}><span>{m.round}</span><strong>{findPlayer(universe,m.winnerId)?fullName(findPlayer(universe,m.winnerId)):'Winner'}</strong><b>{m.score}</b></button>)}</div></section>}<section className="draw-board">{Object.entries(byRound).map(([round,matches])=><div className="draw-column" key={round}><h3>{round}</h3>{matches.map(m=>{const w=findPlayer(universe,m.winnerId),l=findPlayer(universe,m.loserId);return <button key={m.id} onClick={()=>onMatch(edition.id,m.id)}><div><strong>{w?fullName(w):'Winner'}</strong><span>{l?fullName(l):'Opponent'}</span></div><b>{m.score}</b><small>{m.tags?.join(' · ')||m.explanation}</small></button>})}</div>)}</section></>:<EmptyState>No completed edition for {year}. Use the Overview tab to simulate to this event.</EmptyState>}</>}

    {tab==='History'&&<><section className="panel"><h3>Champions and finalists</h3>{family.editions.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Year</th><th>Champion</th><th>Finalist</th><th>Final score</th><th>Surface</th><th>Draw</th></tr></thead><tbody>{family.editions.map(e=>{const final=e.matches?.find(m=>m.round==='F');return <tr key={e.id}><td>{e.event.year}</td><td><Flag code={e.championCountry}/><button className="player-link" onClick={()=>onPlayer(e.championId)}>{e.championName}</button></td><td><button className="player-link" onClick={()=>onPlayer(e.finalistId)}>{e.finalistName}</button></td><td>{final?.score||'—'}</td><td><SurfaceBadge surface={e.event.surface}/></td><td>{e.drawSize}</td></tr>})}</tbody></table></div>:<EmptyState>History begins after the first edition.</EmptyState>}</section><div className="two-column"><section className="panel"><h3>Repeat winners</h3>{repeatWinners.length?repeatWinners.slice(0,12).map((r,i)=><button className="leader-row" key={r.player.id} onClick={()=>onPlayer(r.player.id)}><span>{i+1}</span><Flag code={r.player.country}/><strong>{fullName(r.player)}</strong><b>{r.value}</b></button>):<p className="muted">No repeat champion yet.</p>}</section><section className="panel"><h3>Notable finals</h3>{notableFinals.length?notableFinals.slice(0,10).map(({edition:e,match})=><button className="history-row clickable" key={e.id} onClick={()=>onMatch(e.id,match.id)}><strong>{e.event.year}</strong><span>{e.championName} def. {e.finalistName}</span><small>{match.tags?.join(' · ')||match.explanation}</small></button>):<p className="muted">No tagged classic final yet.</p>}</section></div></>}

    {tab==='Stats'&&<><section className="detail-stat-grid"><Stat label="Editions" value={stats.editions.length}/><Stat label="Youngest champion" value={stats.youngest?`${fullName(stats.youngest.player)}, ${stats.youngest.age}`:'—'}/><Stat label="Oldest champion" value={stats.oldest?`${fullName(stats.oldest.player)}, ${stats.oldest.age}`:'—'}/><Stat label="Most aces in a match" value={stats.mostAces?.aces||'—'}/></section><div className="two-column"><Leader title="Most titles" rows={stats.titleLeaders} onPlayer={onPlayer}/><Leader title="Most match wins" rows={stats.winLeaders} onPlayer={onPlayer}/><Leader title="Most appearances" rows={stats.matchLeaders} onPlayer={onPlayer}/><Leader title="Most five-set wins" rows={stats.fiveSetLeaders} onPlayer={onPlayer}/><section className="panel"><h3>Country leaders</h3>{stats.countryLeaders.slice(0,12).map(([code,value])=><div className="split-row" key={code}><span><Flag code={code}/>{countryByCode(code).name}</span><strong>{value}</strong></div>)}</section></div></>}
  </div>;
}

function TeamTournamentView({universe,tour,name,family,event,edition,year,setYear,availableYears,tab,setTab,onBack,onPlayer,onSimulate}){
 const previous=family.editions.find(e=>e.event.year<universe.year),rounds=(edition?.matches||[]).reduce((g,m)=>{(g[m.round]??=[]).push(m);return g;},{}),titles=new Map();
 for(const e of family.editions)titles.set(e.championCountry,(titles.get(e.championCountry)||0)+1);
 const leaders=[...titles.entries()].sort((a,b)=>b[1]-a[1]);
 const finalist=edition?.matches?.find(m=>m.round==='F')?.loser;
 return <div className="page detail-page"><BackButton onBack={onBack} label="Back to previous page"/><header className="tournament-hero"><div><p>{tour} · National teams</p><h1>{name}</h1><span>{event.location} · Week {event.week}</span></div><span className="team-cup-mark">TEAM CUP</span></header><Tabs items={['Overview','Current Year','History','Stats']} active={tab} onChange={setTab}/>
 {tab==='Overview'&&<><section className="detail-stat-grid"><Stat label="Format" value="16-country finals"/><Stat label="Tour" value={tour}/><Stat label="Week" value={event.week}/><Stat label="Surface" value={event.surface}/><Stat label="Roster" value="Four players"/><Stat label="Defending nation" value={previous?.championCountry?countryByCode(previous.championCountry).name:'First edition'}/></section>{edition?<section className="champion-banner"><span>{year} champions</span><strong><Flag code={edition.championCountry}/>{countryByCode(edition.championCountry).name}</strong><p>defeated {finalist?countryByCode(finalist).name:'the finalist'}</p></section>:<section className="panel upcoming-edition"><h3>Upcoming national-team finals</h3><p>The sixteen strongest available nations select four-player squads. Team quality, depth, form and health determine each tie.</p>{event.year===universe.year&&event.week>=universe.week&&!universe.seasonEnded&&<button className="primary-action" onClick={()=>onSimulate?.(event.week)}>Simulate to {name}</button>}</section>}</>}
 {tab==='Current Year'&&<><div className="edition-selector"><label>Edition <select value={year} onChange={e=>setYear(Number(e.target.value))}>{availableYears.map(y=><option key={y}>{y}</option>)}</select></label></div>{edition?<section className="team-draw">{Object.entries(rounds).map(([round,ties])=><div className="draw-column" key={round}><h3>{round}</h3>{ties.map((tie,i)=><article key={`${round}-${i}`}><div><Flag code={tie.winner}/><strong>{countryByCode(tie.winner).name}</strong><b>{tie.score}</b></div><div><Flag code={tie.loser}/><span>{countryByCode(tie.loser).name}</span></div><small>Winning squad</small><div className="team-roster-links">{(tie.winnerRoster||[]).map(id=>{const p=findPlayer(universe,id);return p?<button key={id} onClick={()=>onPlayer(id)}>{fullName(p)}</button>:null})}</div></article>)}</div>)}</section>:<EmptyState>No completed edition for {year}.</EmptyState>}</>}
 {tab==='History'&&<section className="panel"><h3>Champions and finalists</h3>{family.editions.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Year</th><th>Champion</th><th>Finalist</th><th>Final score</th></tr></thead><tbody>{family.editions.map(e=>{const f=e.matches?.find(m=>m.round==='F');return <tr key={e.id}><td>{e.event.year}</td><td><Flag code={e.championCountry}/>{countryByCode(e.championCountry).name}</td><td><Flag code={f?.loser}/>{f?.loser?countryByCode(f.loser).name:'—'}</td><td>{f?.score||'—'}</td></tr>})}</tbody></table></div>:<EmptyState>History begins after the first edition.</EmptyState>}</section>}
 {tab==='Stats'&&<div className="two-column"><section className="panel"><h3>Most titles by nation</h3>{leaders.map(([country,count],i)=><div className="leader-row static" key={country}><span>{i+1}</span><Flag code={country}/><strong>{countryByCode(country).name}</strong><b>{count}</b></div>)}</section><section className="panel"><h3>Stored team records</h3><Stat label="Editions" value={family.editions.length}/><Stat label="Countries crowned" value={leaders.length}/><Stat label="Ties stored" value={family.editions.reduce((sum,e)=>sum+(e.matches?.length||0),0)}/><Stat label="Latest champion" value={family.editions[0]?.championCountry?countryByCode(family.editions[0].championCountry).name:'—'}/></section></div>}
 </div>;
}

function championPoints(level){return LEVEL_POINTS[level]??({'Junior Slam':1000,'Junior Finals':750,'Junior 500':500,Continental:400}[level]||0);}
function DoublesTournamentView({universe,tour,name,family,event,edition,year,setYear,availableYears,tab,setTab,onBack,onPlayer,onMatch,onSimulate}){
 const previous=family.editions.find(e=>e.event.year<universe.year);
 const byRound=(edition?.matches||[]).reduce((g,m)=>{(g[m.round]??=[]).push(m);return g;},{});
 const titleCounts=new Map();for(const e of family.editions){const key=e.championNames?.join(' / ')||e.championTeamId;titleCounts.set(key,(titleCounts.get(key)||0)+1);}const leaders=[...titleCounts.entries()].sort((a,b)=>b[1]-a[1]);
 const longest=family.editions.flatMap(e=>(e.matches||[]).map(m=>({...m,edition:e}))).sort((a,b)=>(b.durationMinutes||0)-(a.durationMinutes||0))[0];
 return <div className="page detail-page"><BackButton onBack={onBack} label="Back to previous page"/><header className="tournament-hero"><div><p>{tour} · {event.level} doubles</p><h1>{name}</h1><span>{event.location} · {event.dates||`Week ${event.week}`}</span></div><SurfaceBadge surface={event.surface}/></header><Tabs items={['Overview','Current Year','History','Stats']} active={tab} onChange={setTab}/>
 {tab==='Overview'&&<><section className="detail-stat-grid"><Stat label="Location" value={event.location}/><Stat label="Surface" value={event.surface}/><Stat label="Level" value={event.level}/><Stat label="Draw" value={event.drawSize}/><Stat label="Team chemistry" value="Active"/><Stat label="Week" value={event.week}/><Stat label="Defending champions" value={previous?.championNames?.join(' / ')||'First edition'}/><Stat label="Status" value={edition?'Completed':'Upcoming'}/></section>{edition?<section className="champion-banner"><span>{year} champions</span><strong>{edition.championNames.join(' / ')}</strong><p>defeated {edition.finalistNames?.join(' / ')}</p></section>:<section className="panel upcoming-edition"><h3>Upcoming doubles edition</h3><p>Teams are selected from permanent partnerships, semi-regular pairs, dedicated doubles specialists and eligible singles crossovers. Chemistry and schedule overlap determine access.</p>{event.year===universe.year&&event.week>=universe.week&&!universe.seasonEnded&&<button className="primary-action" onClick={()=>onSimulate?.(event.week)}>Simulate to {name}</button>}</section>}</>}
 {tab==='Current Year'&&<><div className="edition-selector"><label>Edition <select value={year} onChange={e=>setYear(Number(e.target.value))}>{availableYears.map(y=><option key={y}>{y}</option>)}</select></label></div>{edition?<section className="draw-board">{Object.entries(byRound).map(([round,matches])=><div className="draw-column" key={round}><h3>{round}</h3>{matches.map(m=>{const wt=findDoublesTeam(universe,m.winnerId),lt=findDoublesTeam(universe,m.loserId),winnerNames=m.winnerNames||wt?.playerNames||['Winning team'],loserNames=m.loserNames||lt?.playerNames||['Opponents'];return <button key={m.id} onClick={()=>onMatch(edition.id,m.id)}><div><strong>{winnerNames.join(' / ')}</strong><span>{loserNames.join(' / ')}</span></div><b>{m.score}</b><small>{m.tags?.join(' · ')||'Doubles match'}</small></button>})}</div>)}</section>:<EmptyState>No completed doubles edition for {year}.</EmptyState>}</>}
 {tab==='History'&&<section className="panel"><h3>Champions and finalists</h3>{family.editions.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Year</th><th>Champions</th><th>Finalists</th><th>Draw</th></tr></thead><tbody>{family.editions.map(e=><tr key={e.id}><td>{e.event.year}</td><td>{e.championNames.join(' / ')}</td><td>{e.finalistNames?.join(' / ')||'—'}</td><td>{e.drawSize}</td></tr>)}</tbody></table></div>:<EmptyState>History begins after the first edition.</EmptyState>}</section>}
 {tab==='Stats'&&<><section className="detail-stat-grid"><Stat label="Editions" value={family.editions.length}/><Stat label="Different champions" value={titleCounts.size}/><Stat label="Longest stored match" value={longest?.durationMinutes?`${Math.floor(longest.durationMinutes/60)}h ${longest.durationMinutes%60}m`:'—'}/><Stat label="Largest draw" value={Math.max(0,...family.editions.map(e=>e.drawSize||0))}/></section><div className="two-column"><section className="panel"><h3>Most titles by partnership</h3>{leaders.slice(0,15).map(([team,count],i)=><div className="leader-row static" key={team}><span>{i+1}</span><strong>{team}</strong><b>{count}</b></div>)}</section><section className="panel"><h3>Current partnership access</h3>{(universe.doublesTeams[tour]||[]).slice(0,12).map(t=><div className="leader-row static" key={t.id}><span>{t.ranking}</span><strong>{t.playerNames.join(' / ')}</strong><small>{t.type} · chemistry {Math.round(t.chemistry)}</small></div>)}</section></div></>}
 </div>;
}
function Leader({title,rows,onPlayer}){return <section className="panel"><h3>{title}</h3>{rows.slice(0,12).map((r,i)=><button className="leader-row" key={r.player.id} onClick={()=>onPlayer(r.player.id)}><span>{i+1}</span><Flag code={r.player.country}/><strong>{fullName(r.player)}</strong><b>{r.value}</b></button>)}</section>}
